streamx.blueprints.indexable-resources-producer.index-fragments=false

streamx.blueprints.indexable-resources-producer.include-facets=true
streamx.blueprints.indexable-resources-producer.configurations.eds.selector=meta[property^=facets:]
streamx.blueprints.indexable-resources-producer.configurations.eds.keys=property
streamx.blueprints.indexable-resources-producer.configurations.eds.key-delimiter=facets:
streamx.blueprints.indexable-resources-producer.configurations.eds.values=content

streamx.blueprints.indexable-resources-producer.configurations.color.single-attr=true
streamx.blueprints.indexable-resources-producer.configurations.color.selector=div.test
streamx.blueprints.indexable-resources-producer.configurations.color.keys=color

streamx.blueprints.indexable-resources-producer.configurations.nested.selector=meta[name^=facets:]
streamx.blueprints.indexable-resources-producer.configurations.nested.keys=name
streamx.blueprints.indexable-resources-producer.configurations.nested.key-delimiter=facets:
streamx.blueprints.indexable-resources-producer.configurations.nested.values=value
streamx.blueprints.indexable-resources-producer.configurations.nested.hierarchical-facet-delimiter=>